# Generated by Django 5.0 on 2026-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusagelog',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
