# Generated by Django 5.0 on 2026-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_chatusagelog_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_key_index', models.IntegerField(default=0)),
            ],
        ),
    ]
