# Generated by Django 5.0 on 2026-02-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('other', 'Other')], max_length=20)),
                ('cpu_platform', models.CharField(choices=[('am4', 'AMD AM4'), ('am5', 'AMD AM5'), ('intel_8_9', 'Intel 8th–9th Gen'), ('intel_10_11', 'Intel 10th–11th Gen'), ('intel_12_13_14', 'Intel 12th–14th Gen'), ('apple_silicon', 'Apple Silicon (M-series)'), ('unknown', 'Not sure')], default='unknown', max_length=30)),
                ('gpu_brand', models.CharField(choices=[('nvidia', 'NVIDIA'), ('amd', 'AMD'), ('intel', 'Intel'), ('apple', 'Apple (Integrated)'), ('none', 'No dedicated GPU / Integrated'), ('unknown', 'Not sure')], default='unknown', max_length=20)),
                ('issue_title', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting for Parts'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('location', models.CharField(help_text='Dorm, apartment, or campus location', max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
